server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  output:
    ansi:
      enabled: always

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/public_data?serverTimezone=Asia/Seoul
      username: public_data
      password: java1234!

      hikari:
        connection-timeout: 58000
        max-lifetime: 118000

    h2:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost/~/public_data
      username: public_data
      password: java1234!

      console:
        enabled: true
        path: /h2-console

      hikari:
        connection-timeout: 58000
        max-lifetime: 118000

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

topis:
  scheme: https
  host:

